{{- if eq .Values.workload.type "cronjob" }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "chart-base.fullname" . }}
  labels:
    {{- include "chart-base.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjob.schedule | quote }}
  {{- with .Values.cronjob.timeZone }}
  timeZone: {{ . | quote }}
  {{- end }}
  concurrencyPolicy: {{ .Values.cronjob.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    metadata:
      labels:
        {{- include "chart-base.podLabels" . | nindent 8 }}
    spec:
      backoffLimit: {{ .Values.job.backoffLimit }}
      {{- with .Values.job.activeDeadlineSeconds }}
      activeDeadlineSeconds: {{ . | int64 }}
      {{- end }}
      template:
        metadata:
          labels:
            {{- include "chart-base.podLabels" . | nindent 12 }}
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
        spec:
          {{- include "chart-base.podSpec" (dict "ctx" . "restartPolicy" "Never") | nindent 10 }}
{{- end }}
