{{- if eq .Values.workload.type "deployment" }}
{{- $fullname := include "chart-base.fullname" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "chart-base.labels" . | nindent 4 }}
  {{- with include "chart-base.reloaderAnnotations" . | trim }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds | int64 }}
  {{- if not (kindIs "invalid" .Values.minReadySeconds) }}
  minReadySeconds: {{ .Values.minReadySeconds | int64 }}
  {{- end }}
  {{- if not (kindIs "invalid" .Values.revisionHistoryLimit) }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | int64 }}
  {{- end }}
  {{- with .Values.strategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart-base.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart-base.podLabels" . | nindent 8 }}
      {{- if or .Values.config .Values.configFiles.files .Values.podAnnotations }}
      annotations:
        {{- if .Values.config }}
        checksum/config-env: {{ (include (print $.Template.BasePath "/configmap-env.yaml") . | fromYaml).data | toJson | sha256sum }}
        {{- end }}
        {{- if .Values.configFiles.files }}
        checksum/config-files: {{ (include (print $.Template.BasePath "/configmap-files.yaml") . | fromYaml).data | toJson | sha256sum }}
        {{- end }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
    spec:
      {{- include "chart-base.podSpec" (dict "ctx" .) | nindent 6 }}
{{- end }}
