{{- if and (eq .Values.workload.type "deployment") .Values.metrics.enabled .Values.service.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chart-base.fullname" . }}
  labels:
    {{- include "chart-base.labels" . | nindent 4 }}
    {{- with .Values.metrics.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "chart-base.selectorLabels" . | nindent 6 }}
  endpoints:
    {{- include "chart-base.metricsEndpoint" . | nindent 4 }}
{{- end }}
